TECH-558: Added cucumber tests for GET /services
GovStackWorkingGroup/bb-registration pull request #14
Opened 2023-04-17 13:32 UTC by KarolinaKopacz

**Description:**
Add cucumber test for GET /services.

Ticket: https://govstack-global.atlassian.net/browse/TECH-558

2023-04-17 13:39 UTC, KarolinaKopacz commented
@ingmarvali 
The `serviceKey` property is required in the schema, but there is no serviceKey in the properties - does that mean that `id` should be required because the id description contains information about the service key?
If so, I can update the API spec and change `serviceKey` to `id` in the list of required fields

<img width="482" alt="Zrzut ekranu 2023-04-17 o 15 34 11" src="https://user-images.githubusercontent.com/80507519/232499960-9f0d84b7-d770-4ba7-86cd-73d25dee34c8.png">

2023-04-17 15:35 UTC, mgrochalskisoldevelo requested changes

2023-04-17 15:35 UTC, mgrochalskisoldevelo commented on test/openAPI/features/services_services.feature
> +    When User sends GET request with given "Register Mother and Child" as name
smoke test should be invoked without optional parameters to retrieve a list of all services.

2023-04-17 15:35 UTC, mgrochalskisoldevelo commented on test/openAPI/features/services_services.feature
> +  Scenario Outline: Retrieve the list of services
Here i believe only those services are returned that match the name provided in optional parameter. I would change the scenario name to be more descriptive

2023-04-17 15:35 UTC, mgrochalskisoldevelo commented on test/openAPI/features/services_services.feature
> +
We should also check here if services that we received (if any) match with the name that we provided in the optional parameter

2023-04-17 15:35 UTC, mgrochalskisoldevelo commented on test/openAPI/features/support/services_services.js
> +const { Given, When, Then, Before } = require('@cucumber/cucumber');
Missing After with its code

2023-04-18 21:38 UTC, mgrochalskisoldevelo requested changes
Except those 2 comments. Have you checked if 
```
 And The service name in response match provided "<name>" as name parameter
```
will check all the elements returned. Or is it going to check just the first one. I believe there can be more objects returned with the same name but different versions. Please confirm that it will work for both cases (one returned element and more than one)

2023-04-18 21:38 UTC, mgrochalskisoldevelo commented on test/openAPI/features/services_services.feature
> +    When User sends GET /statistics request with no optional parameter
```suggestion
    When GET request to retrieve a list of services is sent
```
I think it sounds better than with no optional parameter

2023-04-18 21:38 UTC, mgrochalskisoldevelo commented on test/openAPI/features/services_services.feature
> +    And The service name in response match provided "<name>" as name parameter
```suggestion
       And The name field in the response matches with "<name>" provided as name in the query parameter
       or simply
       And The response is filtered by "<name>" provided in the optional parameter
```

or something similar

2023-04-19 11:29 UTC, mgrochalskisoldevelo requested changes
I like the approach. I saw just 2 more issues.

1. It will always fail when there will be no element returned, should we skip the test? or we assume that there will be always at least 1 element matching the name in the request. What do you think about it @KarolinaKopacz ?

2. You used .includes and I assume that is why:  
![image](https://user-images.githubusercontent.com/119664031/233060787-96a12a44-2606-4f28-b7ab-bba3a3f5a3e1.png)

When you will put When - which is invoking .withQueryParams into brackets {} it should return single value: 
![image](https://user-images.githubusercontent.com/119664031/233061437-97f87b3c-e7fc-47ef-b888-ed87201ce44f.png)

Don't ask me why, but it seems it works like that.

2023-04-20 08:28 UTC, mgrochalskisoldevelo approved these changes

2023-04-21 19:21 UTC, ingmarvali approved these changes
seems ok

2023-04-24 08:26 UTC, merged