TECH-559: Add Tests For GET /services/serviceId
GovStackWorkingGroup/bb-registration pull request #17
Opened 2023-05-15 02:07 UTC by mdulko

Ticket: https://govstack-global.atlassian.net/browse/TECH-559

2023-05-15 08:43 UTC, KarolinaKopacz requested changes

2023-05-15 08:43 UTC, KarolinaKopacz commented on examples/mock/mockoon-registration.json
> +      "endpoint": "services/{serviceId}",
```suggestion
      "endpoint": "services/:serviceId",
```

2023-05-15 08:43 UTC, KarolinaKopacz commented on test/openAPI/features/support/helpers/service_serviceId.js
> +});
```suggestion
Then(/^The \/services\/\{serviceId\} response should have status (\d+)$/, (status) => 
  specServiceId.response().to.have.status(status)
);
```

2023-05-15 08:43 UTC, KarolinaKopacz commented on test/openAPI/features/support/helpers/helpers.js
> +  serviceIdEndpoint: 'services/{serviceId}'
Please add above comment `// service_serviceId`
and also we can moved `serviceSchema` to the end of the file  and add comment `// shares`

2023-05-15 08:43 UTC, KarolinaKopacz commented on test/openAPI/features/services_serviceId.feature
> +    Given User wants to retrieve the service
```suggestion
    Given User wants to retrieve all the information about the service
```

2023-05-16 08:51 UTC, KarolinaKopacz approved these changes

2023-05-18 13:28 UTC, dbienkowska commented
@ingmarvali could you please review this PR?

2023-05-18 19:11 UTC, ingmarvali approved these changes

2023-05-19 06:58 UTC, merged