TECH-562: Add cucumber test for Registration - Applicant - POST /services/{serviceId}/applications
GovStackWorkingGroup/bb-registration pull request #18
Opened 2023-05-17 16:41 UTC by mgrochalskisoldevelo

Added cucumber tests, mocks and gherkin scenarios for POST /services/:serviceId/applications endpoint

TICKET: https://govstack-global.atlassian.net/browse/TECH-562

2023-05-18 07:07 UTC, KarolinaKopacz requested changes

2023-05-18 07:07 UTC, KarolinaKopacz commented on test/openAPI/features/applicant_services_serviceid_applications.feature
> +    When POST request to submit an application is sent with given I-M-C header and "f7d33db0-2809-484e-a780-76b7ccd4ecbf" as serviceId parameter
Not all user can be familiar what the I-M-C means
```suggestion
    When POST request to submit an application is sent with given Information-Mediator-Client header and "f7d33db0-2809-484e-a780-76b7ccd4ecbf" as serviceId parameter
```

2023-05-18 07:07 UTC, KarolinaKopacz commented on test/openAPI/features/support/helpers/helpers.js
> +  // services/{serviceId}/applications
```suggestion
  // applicant_services_serviceid_applications
```

2023-05-18 07:07 UTC, KarolinaKopacz commented on test/openAPI/features/support/helpers/helpers.js
> +  // data statistics
```suggestion
  // data_statistics
```

2023-05-18 07:07 UTC, KarolinaKopacz commented on test/openAPI/features/support/helpers/helpers.js
> +  // services
```suggestion
  // services_services
```

2023-05-18 07:07 UTC, KarolinaKopacz commented on test/openAPI/features/support/helpers/helpers.js
> +  // data statistics
To be consistent with another helpers.js files use here the test file name

2023-05-18 19:11 UTC, ingmarvali approved these changes

2023-05-19 12:40 UTC, KarolinaKopacz approved these changes

2023-05-19 12:40 UTC, merged