TECH-563: Add cucumber test for Registration - Applicant -  POST /documents
GovStackWorkingGroup/bb-registration pull request #19
Opened 2023-05-22 14:09 UTC by mgrochalskisoldevelo

Added mocks, cucumber tests and gherkin scenarios for /documents endpoint

TICKET: https://govstack-global.atlassian.net/browse/TECH-563

2023-05-22 18:52 UTC, ingmarvali approved these changes

2023-05-23 08:11 UTC, KarolinaKopacz requested changes

2023-05-23 08:11 UTC, KarolinaKopacz commented on test/openAPI/features/support/applicant_documents.js
> +When(
Add empty space above, please

2023-05-23 08:11 UTC, KarolinaKopacz commented on test/openAPI/features/applicant_documents.feature
> +    When POST request to upload a document with given "V2UgbG92ZSBqc29uIQ==" as an item of the file array is sent
I see that in example in the API spec there is this string but maybe should be a document or image? 
This test title `a document with given "V2UgbG92ZSBqc29uIQ==" as an item of the file array` is misleading. 
`POST request  with given document is sent` - this is how I see it. And also better send the object (in base64 format) for example:
```
{
  fieldname: 'image',
  originalname: 'Screenshot 2021-11-02 at 00.12.28.png',
  encoding: '7bit',
  mimetype: 'image/png',
  destination: 'uploads/',
  filename: 'a15af77a31eb44b4a6b043db90f15214',
  path: 'uploads/a15af77a31eb44b4a6b043db90f15214',
  size: 538524
}
```

2023-05-24 13:24 UTC, KarolinaKopacz approved these changes

2023-05-25 06:22 UTC, merged