TECH-567: Cucumber tests for GET /tasks/{taskId}
GovStackWorkingGroup/bb-registration pull request #24
Opened 2023-06-01 12:35 UTC by mdulko

Ticket: https://govstack-global.atlassian.net/browse/TECH-567

2023-06-02 06:42 UTC, KarolinaKopacz commented on test/openAPI/features/support/helpers/helpers.js
> +        // format: 'uuid',
This line should be remove?

2023-06-02 07:02 UTC, KarolinaKopacz requested changes

2023-06-02 07:02 UTC, KarolinaKopacz commented on test/openAPI/features/applicant_tasks_taskid.feature
> +    When GET request to get task is sent with given "81c4445c-bff6-11ed-afa1-0242ac120002" as taskId parameter
There is no "81c4445c-bff6-11ed-afa1-0242ac120002" taskId in the test-data.json file. Please add it.
Also don't use the same ids in a different tests ;)

2023-06-02 10:04 UTC, KarolinaKopacz approved these changes

2023-06-04 08:13 UTC, ingmarvali approved these changes

2023-06-05 07:26 UTC, merged