TECH-561: Cucumber tests for GET /eForms/{eFormsId}
GovStackWorkingGroup/bb-registration pull request #26
Opened 2023-06-02 12:27 UTC by mdulko

Ticket: https://govstack-global.atlassian.net/browse/TECH-561

2023-06-02 12:54 UTC, KarolinaKopacz requested changes

2023-06-02 12:54 UTC, KarolinaKopacz commented on test/openAPI/test-data.json
> +  "eForms": [
I think eForms should be part of service object, not separate object.

2023-06-02 13:14 UTC, KarolinaKopacz approved these changes

2023-06-04 08:14 UTC, ingmarvali approved these changes

2023-06-05 07:31 UTC, merged